### ISSUE TITLE
Expected and actual swapped?

### ISSUE THREAD

**Issue by wiseman** [pjstadig/humane-test-output#1]
I have the following test:

```
(is (= (count (:results r)) 4))
```

 Without `humane-test-output` it fails with

```
expected: (= (count (:results r)) 4)
  actual: (not (= 3 4))
```

With `humane-test-output` it fails with

```
expected: 3
  actual: 4
    diff: - 3
          + 4
```

I am using version 0.6.0 of `humane-test-output`, version 1.5.1 of clojure.

**Comment by jakemcc** [comment]
Documentation for clojure.test [is](http://clojure.github.io/clojure/clojure.test-api.html#clojure.test/is) has the expected value coming first. 

`(is (= expected actual))`

**Comment by pjstadig** [comment]
Yeah, I patterned the output after what clojure.test has documented.
