### ISSUE TITLE
No effect (by default, as README suggests) in ClojureScript

### ISSUE THREAD

**Issue by lvh** [pjstadig/humane-test-output#15]
I have 0.8.0 enabled with the `activate!` call. Works fine in Clojure. When running ClojureScript tests, it doesn't have any effect:

```
FAIL in (icon-test) (:)
expected: (= {:a 1, :b 2} {:a 1, :c 3})
  actual: (not (= {:a 1, :b 2} {:a 1, :c 3}))
```

That makes sense, because it doesn't appear [doo understands middleware](https://github.com/bensu/doo/issues/85) yet.

How do I run ClojureScript tests so that I do get humane error messages back out?

**Comment by pjstadig** [comment]
AFAIK humane-test-output does not use middleware for ClojureScript support. I didn't actually implement the ClojureScript support.

Do you have any other plugins or dependencies or IDEs that could also be messing with the test output?

**Comment by lvh** [comment]
That particular thing is just output of `lein doo`, so no.

**Comment by nenadalm** [comment]
@lvh 
you need to add following line into your script running tests: https://github.com/pjstadig/humane-test-output/blob/master/test/pjstadig/run_all.cljs#L3

@pjstadig
why didn't you create build on travis after merging this pr: https://github.com/pjstadig/humane-test-output/pull/13/files and removed the status from readme:
https://github.com/pjstadig/humane-test-output/commit/40523c2b65a995dc38bdd18c759b6e3b6ef75d80?

**Comment by lvh** [comment]
Awesome, thanks @nenadalm !

**Comment by pjstadig** [comment]
@nenadalm Sorry for the very late reply. I was trying to remember why I removed the build status, and I think it was because enabling it meant that travis would have access to all my repositories (including work related ones), and I didn't want to allow carte blanche access to travis.

If that has changed or is incorrect, then I can revisit that decision.

**Comment by nenadalm** [comment]
@pjstadig ok, thanks for explanation.
