### ISSUE TITLE
Lumo compatibility

### ISSUE THREAD

**Issue by arichiardi** [pjstadig/humane-test-output#24]
Hi all!

It would be really really awesome to have this working in lumo as well. At the moment it triggers some weird error. I was actually having a look at the code and especially the namespace `.macros`. Except that there are no macros inside...I wanted to ask then if these functions are used at the macro stage (called by `cljs.test` for instance) so that I could try a port...

It looks like it has been a pain to port to Cljs already and wanted to know a bit more :smile: 

Thanks for this btw, I use it literally everywhere.

**Comment by arichiardi** [comment]
I investigated a bit more and it seems like it boils down to an error in `cljs.data`:

```
No such macros namespace: cljs.data, could not locate cljs/data.clj or cljs/data.cljc in file pjstadig/macro.cljc
	 (new)
	 Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:2024:72)
	 Function.cljs.analyzer.error.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:2660:92)
	 Function.cljs.analyzer.error.cljs$core$IFn$_invoke$arity$2 (NO_SOURCE_FILE <embedded>:2659:92)
	 (NO_SOURCE_FILE <embedded>:5662:162)
	 Object.lumo.repl.load_other (NO_SOURCE_FILE <embedded>:6471:378)
	 lumo.repl.load (NO_SOURCE_FILE <embedded>:6475:96)
	 Function.cljs.js.require.cljs$core$IFn$_invoke$arity$5 (NO_SOURCE_FILE <embedded>:5664:77)
	 (NO_SOURCE_FILE <embedded>:5699:463)
	 (NO_SOURCE_FILE <embedded>:5663:394)
```

**Comment by arichiardi** [comment]
PR #27 open for this. Ping @pjstadig.

**Comment by pjstadig** [comment]
I'd like to understand the root cause here. Why can `cljs.data` not be found? I'm barely functional with clojurescript, and have not heard of lumo before.

**Comment by arichiardi** [comment]
I think that even with the `cljs.data` problem gone, the main is that the current solution does not define the defmethod correctly in self-host (and apparently in some cases also with vanilla cljs).

**Comment by arichiardi** [comment]
Sorry @pjstadig lumo is an implementation of a ClojureScript self-host REPL, I actually realized that probably I had two duplicate issues there. A couple of answers to the closed PR, continuing the discussion as per your request:

1. I politely disagree on this one. Assert-expr, as the name suggests, is meant to only assert and it is called in a macro context that is notoriously less composable and as folks reported it is not working fine in ClojureScript. Note that this does not happen in the IDE for me but at the terminal.

2. As above, working in a terminal is my goal. The problem manifests itself in a terminal when inspecting ClojureScript tests.

3. I understand this would break some users of your code, which is not good.

I think therefore that the path forward can be, with your consent, to have a fork with the other approach, cljs specific. I think. Ideas?

/cc @ryfow

**Comment by pjstadig** [comment]
What would be the correct way to define the defmethod in self host and/or vanilla cljs? Is there not a portable, compatible way to do it?

I'm willing to work through the issues to keep clj and cljs together. I'd prefer not to fracture the clojure/clojurescript vanilla/clojurescript self-host communities more.

**Comment by ryfow** [comment]
My issues with the `assert-expr` implementation weren't ide related either but I never got the the bottom of what exactly was going on other than sometimes I just didn't get humane output on failing tests. My guess was that my `=` wasn't always exactly the same as the ``=` that was defmethoded, due to class loading oddities but I don't have anything to back that up.

Could we use the `assert-expr` for the bonus feature in clj, but `report-`/`convert-event` for the diff extraction on all platforms?

**Comment by arichiardi** [comment]
I thought I was on the right path when I tried. Need to debug more, not sure I will have time these days.
Probably your last line @ryfow is the best of both worlds? We can try of course and see what happens :smile:

**Comment by arichiardi** [comment]
@pjstadig I am maintaining my own fork, which I published on npm but still interested in proper ClojureScript support here, any additional thought on @ryfow's suggestion?

**Comment by pjstadig** [comment]
@arichiardi @ryfow I think the solution of having the bonus feature in the defmethod and report for diff extraction is a good compromise. Do you have an implementation of it that I can merge?

**Comment by arichiardi** [comment]
I think my fork needs some work after the last refactoring. So at the moment the answer is no but I will try my best.

**Comment by arichiardi** [comment]
wait a sec

~this happens on `master`:~

~Maybe #29 improved stuff so much that no `lumo` works :open_mouth:~

No scratch that, it is my work on top of #29

**Comment by arichiardi** [comment]
This is done in [0.9.0](https://github.com/pjstadig/humane-test-output/commit/92a31187593ef6a827a6840ee0259067364398ba) awesome!
