### ISSUE TITLE
Make report- public

### ISSUE THREAD

**Issue by arichiardi** [pjstadig/humane-test-output#28]
Sometimes you need to compose `humane-test-output` with some other library (`expound`?) and I was wondering what would be the best approach for that.

It seems to me that the `report-` function could be exposed so that it can be used in custom `defmethod test/report`.

What do you think? Any other suggestion?

**Comment by pjstadig** [comment]
I'm not prepared to make `report-` public at this point. I think some things need to be cleaned up before I'm willing to let people depend on any implementation details. For now the workaround is to use the `@#'report-` hack to access a private var.

**Comment by arichiardi** [comment]
@pjstadig would you be open to reopen this issue :smile: 

I think in terms of composability to have a public function for reporting purposes is a good thing. The use case being combine your report with additional reports (like `expound`).

The workaround is not working in ClojureScript here:

```
Unable to resolve var: -report in this context at line 1 my/test_util.cljs
```
