### ISSUE TITLE
Support for Clojurescript

### ISSUE THREAD

**Issue by lvh** [pjstadig/humane-test-output#3]
Clojurescript now has cljs.test. It'd be great if we can get the same awesome test output there :)

**Comment by lvh** [comment]
FWIW, reagent-project/reagent-template includes it but I can't tell if it actually works...

**Comment by arichiardi** [comment]
:+1:

**Comment by pjstadig** [comment]
I'd like to see this work, if it is possible. humane-test-output does Clojure specific not-so-nice things to `clojure.test`. If someone wants to take a crack at it and submit a PR, I'd gladly take a look at it.

**Comment by nenadalm** [comment]
I started looking into it. It sort of works (there are just some excessive newlines...) And everything is duplicated into cljs (for now).

currently it is required to require some additional stuff in tests like do-report: https://github.com/pjstadig/humane-test-output/compare/80f91373bbcc08a0bf24f0b4d18c222d5f105a67...nenadalm:clojurescript_support#diff-20936c87d473fea7e5d6351a664d091fR3

as I can't figure how to do that without these additional stuff here:
https://github.com/pjstadig/humane-test-output/compare/80f91373bbcc08a0bf24f0b4d18c222d5f105a67...nenadalm:clojurescript_support#diff-b85b3975b3dcdfd66cef6f3f0eb0a941R1

I am starting with clojure/clojurescript - so if anybody is willing to help...

I also included some files into `test/fixtures/` which can be used to test if output stays the same after modifying code

``` shell
$ lein test | diff test/fixtures/test_output -
$ lein cljsbuild test 2>&1 | diff test/fixtures/test_output_cljs -
```

**Comment by nenadalm** [comment]
Now files are merged and excessive requires are removed.

Except I accidentaly created 2 files in namespace pjstadig.macro and when renaming the on from test/ it stops working.

**Comment by pjstadig** [comment]
@nenadalm would you mind creating a PR so we can start a conversation around your changes. Thanks for taking this on!

**Comment by nenadalm** [comment]
done. np (it doesn't work anyway yet)
