### ISSUE TITLE
Release with the new ClojureScript part?

### ISSUE THREAD

**Issue by arichiardi** [pjstadig/humane-test-output#35]
Hi @pjstadig!

I was wondering if we could release the latest master with the new ClojureScript commits, maybe `0.9.0` cause theoretically breaking that extra functionality in ClojureScript?

I am using it now with `deps.edn` but it would be great to use it from `lein` as well.

**Comment by pjstadig** [comment]
I'll see if I can get something kicked out.

**Comment by pjstadig** [comment]
Should be released.
