### ISSUE TITLE
Hangs cider 0.9.0 REPL when using tests with doubles

### ISSUE THREAD

**Issue by martintrojer** [pjstadig/humane-test-output#4]
https://github.com/clojure-emacs/cider/issues/1138

**Comment by pjstadig** [comment]
I am unable to reproduce this on either cider 0.9.0 or 0.9.1. Do you have the `clojure-test-mode` package installed?  Perhaps that is interfering?

**Comment by ghost** [comment]
I had the same experience with cider 0.9.1.  Disabling humane test output resolves the problem.  Everything works fine running tests from outside of emacs at the terminal.

**Comment by pjstadig** [comment]
@arkdrag do you have `clojure-test-mode` installed? As I understand it is deprecated, I do not have it installed, and I am unable to reproduce this behavior.
